import { notFound } from "next/navigation";
import { CourseEditor } from "@/components/dashboard/course-editor";
import { CurriculumEditor } from "@/components/dashboard/curriculum-editor";
import { CourseStatusActions } from "@/components/dashboard/course-status-actions";
import { ResourceManager } from "@/components/dashboard/resource-manager";
import { requireInstructor } from "@/lib/auth/helpers";
import { categoryService } from "@/modules/categories/category.service";
import { courseService } from "@/modules/courses/course.service";
import { resourceService } from "@/modules/resources/resource.service";
export default async function EditCoursePage({ params }: { params: Promise<{ id: string }> }) { const user = await requireInstructor(); let course: Awaited<ReturnType<typeof courseService.getForEditor>>; try { course = await courseService.getForEditor((await params).id, user); } catch { notFound(); } let categories: Awaited<ReturnType<typeof categoryService.list>> = []; let resources: Awaited<ReturnType<typeof resourceService.listForCourse>> = []; try { [categories, resources] = await Promise.all([categoryService.list(), resourceService.listForCourse(course._id.toString(), user)]); } catch { } const safeCourse = { ...course, _id: course._id.toString(), categoryId: course.categoryId.toString(), sections: course.sections.map((section) => ({ _id: section._id.toString(), title: section.title, lessons: section.lessons.map((lesson) => ({ _id: lesson._id.toString(), title: lesson.title, type: lesson.type, isPreview: lesson.isPreview })) })) }; const lessons = safeCourse.sections.flatMap((section) => section.lessons.map((lesson) => ({ id: lesson._id, title: `${section.title}: ${lesson.title}` }))); return <section className="p-6 md:p-10"><p className="font-semibold text-indigo-600">{course.status}</p><div className="mt-2 flex flex-wrap items-center justify-between gap-4"><h1 className="text-3xl font-bold">Edit {course.title}</h1><CourseStatusActions courseId={course._id.toString()} status={course.status} /></div><div className="mt-8 grid max-w-5xl gap-7"><div className="rounded-xl border bg-[var(--surface)] p-6"><h2 className="mb-5 text-xl font-bold">Course details & pricing</h2><CourseEditor course={safeCourse} categories={categories.map((category) => ({ _id: category._id.toString(), name: category.name }))} /></div><CurriculumEditor courseId={course._id.toString()} sections={safeCourse.sections} /><ResourceManager courseId={course._id.toString()} lessons={lessons} resources={resources.map((resource) => ({ _id: resource._id.toString(), name: resource.name, lessonId: resource.lessonId.toString(), sizeBytes: resource.sizeBytes }))} /></div></section>; }
