"use client";
import Image from "next/image";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Bookmark, ExternalLink, PlayCircle, Search, Sparkles } from "lucide-react";
type FinderResult={query:string;level?:string;best:{videoId:string;title:string;description:string;channelName:string;thumbnailUrl:string;videoUrl:string;score:number};alternatives:Array<{videoId:string;title:string;channelName:string;thumbnailUrl:string;videoUrl:string;score:number}>;reasoning:string;roadmap:Array<{step:number;title:string;why:string}>;source:string;cached:boolean};
const examples=["Docker","Learn React Hooks","TypeScript generics","System design basics"];
export default function FinderClient(){
 const sp=useSearchParams();const[query,setQuery]=useState(sp.get("q")??"Docker");const[level,setLevel]=useState<"BEGINNER"|"INTERMEDIATE"|"ADVANCED">((sp.get("level") as any)??"BEGINNER");const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);const[result,setResult]=useState<FinderResult|null>(null);const[saved,setSaved]=useState(false);const[saving,setSaving]=useState(false);
 async function search(e?:FormEvent){e?.preventDefault();const q=query.trim();if(!q){setError("Enter a topic to search.");return;}setLoading(true);setError(null);setSaved(false);try{const r=await fetch(`/api/finder/search?q=${encodeURIComponent(q)}&level=${encodeURIComponent(level)}`,{cache:"no-store"});const j=await r.json();if(!r.ok||!j.success)throw new Error(j?.error?.message??"Finder search failed");setResult(j.data as FinderResult);window.history.replaceState(null,"",`/finder?q=${encodeURIComponent(q)}&level=${encodeURIComponent(level)}`);}catch(e){setResult(null);setError(e instanceof Error?e.message:"Finder search failed");}finally{setLoading(false);}}
 useEffect(()=>{void search();},[]);
 const roadmap=useMemo(()=>result?.roadmap??[],[result]);
 async function save(){if(!result||saving||saved)return;setSaving(true);setError(null);try{const r=await fetch("/api/resources/saved",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({videoId:result.best.videoId,title:result.best.title,channelName:result.best.channelName,thumbnailUrl:result.best.thumbnailUrl,videoUrl:result.best.videoUrl,topic:result.query})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j?.error?.message??"Could not save resource");setSaved(true);}catch(e){setError(e instanceof Error?e.message:"Could not save resource");}finally{setSaving(false);}}
 return <div className="mx-auto max-w-6xl px-6 py-12 md:py-16">
  <section className="overflow-hidden rounded-3xl border bg-[linear-gradient(135deg,rgba(79,70,229,0.1),rgba(14,165,233,0.08),rgba(15,23,42,0.03))] p-8 shadow-sm md:p-12"><div className="grid gap-10 lg:grid-cols-[1.2fr_0.8fr] lg:items-center"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full border bg-background/80 px-3 py-1 text-xs font-semibold uppercase tracking-[0.24em] text-[var(--muted)]"><Sparkles className="size-3.5 text-[var(--brand)]"/>AI resource finder</div><h1 className="max-w-2xl text-4xl font-semibold tracking-tight md:text-6xl">What do you want to <span className="text-[var(--brand)]">learn</span>?</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[var(--muted)] md:text-lg">Search real YouTube learning resources and get a ranked learning path.</p><div className="mt-8 flex flex-wrap gap-3">{examples.map(x=><button key={x} type="button" onClick={()=>{setQuery(x);void search();}} className="rounded-full border bg-background/80 px-4 py-2 text-sm font-medium hover:border-[var(--brand)] hover:text-[var(--brand)]">{x}</button>)}</div></div>
  <div className="rounded-2xl border bg-background/90 p-5 shadow-lg"><form className="space-y-4" onSubmit={search}><label className="block text-sm font-medium">Search<div className="mt-2 flex items-center gap-2 rounded-xl border bg-[var(--surface)] px-4 py-3"><Search className="size-4 text-[var(--muted)]"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="Docker, React Hooks, Python basics..."/></div></label><label className="block text-sm font-medium">Level<select value={level} onChange={e=>setLevel(e.target.value as typeof level)} className="mt-2 w-full rounded-xl border bg-[var(--surface)] px-4 py-3 text-sm"><option value="BEGINNER">Beginner</option><option value="INTERMEDIATE">Intermediate</option><option value="ADVANCED">Advanced</option></select></label><button type="submit" disabled={loading} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--brand)] px-4 py-3 text-sm font-semibold text-white disabled:opacity-60"><PlayCircle className="size-4"/>{loading?"Searching…":"Search resources"}</button></form></div></div></section>
  <section className="mt-10 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><div className="rounded-2xl border bg-[var(--surface)] p-6"><h2 className="text-lg font-semibold">Best Resource</h2><p className="text-sm text-[var(--muted)]">{loading?"Searching verified videos...":result?`Source: ${result.source}${result.cached?" · cached":""}`:"No result yet"}</p>{error&&<div className="mt-5 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-700 dark:text-red-300">{error}</div>}{!loading&&result?<article className="mt-6 overflow-hidden rounded-2xl border bg-background"><Image src={result.best.thumbnailUrl} alt={result.best.title} width={1280} height={720} unoptimized className="h-56 w-full object-cover"/><div className="space-y-4 p-5"><div className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--muted)]">Top resource · {result.best.score.toFixed(2)} score</div><h3 className="text-2xl font-semibold leading-tight">{result.best.title}</h3><p className="text-sm leading-6 text-[var(--muted)]">{result.best.description.slice(0,180)}</p><p className="text-sm text-[var(--muted)]">{result.best.channelName}</p><div className="flex flex-wrap gap-3"><Link href={result.best.videoUrl} target="_blank" className="inline-flex items-center gap-2 rounded-xl bg-[var(--brand)] px-4 py-2.5 text-sm font-semibold text-white"><ExternalLink className="size-4"/>Open YouTube</Link><button type="button" disabled={saving||saved} onClick={save} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-semibold disabled:opacity-50"><Bookmark className="size-4"/>{saving?"Saving…":saved?"Saved":"Save"}</button></div></div></article>:null}</div>
  <div className="space-y-6"><section className="rounded-2xl border bg-[var(--surface)] p-6"><h2 className="text-lg font-semibold">Alternative Resources</h2><div className="mt-4 space-y-4">{result?.alternatives.length?result.alternatives.map(x=><article key={x.videoId} className="flex gap-4 rounded-xl border bg-background p-3"><Image src={x.thumbnailUrl} alt={x.title} width={320} height={180} unoptimized className="h-20 w-28 rounded-lg object-cover"/><div className="min-w-0 flex-1"><h3 className="line-clamp-2 text-sm font-semibold">{x.title}</h3><p className="mt-1 text-xs text-[var(--muted)]">{x.channelName}</p><a href={x.videoUrl} target="_blank" rel="noreferrer" className="mt-2 inline-flex text-xs font-semibold text-[var(--brand)]">Open YouTube</a></div></article>):<p className="text-sm text-[var(--muted)]">Alternatives will appear after search.</p>}</div></section><section className="rounded-2xl border bg-[var(--surface)] p-6"><h2 className="text-lg font-semibold">Learning Roadmap</h2><div className="mt-4 space-y-3">{roadmap.length?roadmap.map(s=><div key={s.step} className="rounded-xl border bg-background p-4"><div className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--muted)]">Step {s.step}</div><p className="mt-1 text-sm font-medium">{s.title}</p><p className="mt-1 text-sm text-[var(--muted)]">{s.why}</p></div>):<p className="text-sm text-[var(--muted)]">A roadmap will appear after search.</p>}</div></section></div></section>
 </div>;
}