import { randomUUID } from "crypto";
import { Types } from "mongoose";
import { AppError } from "@/lib/errors/app-error";
import { connectToDatabase } from "@/infrastructure/mongodb/connection";
import { storage } from "@/infrastructure/storage";
import type { PublicUser } from "@/modules/auth/auth.types";
import { Course, type CourseDocument } from "@/modules/courses/course.model";
import { assertCourseOwner, canEditCourse } from "@/modules/courses/course.permissions";
import { enrollmentService } from "@/modules/enrollments/enrollment.service";
import { CourseResource } from "./resource.model";
const extension = (name: string) => name.split(".").pop()?.toLowerCase() || "file";
async function courseForOwner(courseId: string, user: PublicUser): Promise<CourseDocument> { if (!Types.ObjectId.isValid(courseId)) throw new AppError("COURSE_NOT_FOUND", "Course not found", 404); const course = await Course.findById(courseId); if (!course) throw new AppError("COURSE_NOT_FOUND", "Course not found", 404); assertCourseOwner(user, course.instructorId.toString()); return course as CourseDocument; }
export const resourceService = {
  async createUploadIntent(courseId: string, user: PublicUser, input: { lessonId: string; name: string; mimeType: string; sizeBytes: number }) { await connectToDatabase(); const course = await courseForOwner(courseId, user); if (!course.sections.some((section) => section.lessons.some((lesson) => lesson._id.toString() === input.lessonId))) throw new AppError("LESSON_NOT_FOUND", "Lesson not found", 404); const key = `courses/${courseId}/${input.lessonId}/${randomUUID()}.${extension(input.name)}`; return { storageKey: key, uploadUrl: await storage.getSignedUploadUrl(key, input.mimeType), expiresInSeconds: 300 }; },
  async register(courseId: string, user: PublicUser, input: { lessonId: string; name: string; storageKey: string; mimeType: string; sizeBytes: number }) { await connectToDatabase(); const course = await courseForOwner(courseId, user); if (!input.storageKey.startsWith(`courses/${courseId}/${input.lessonId}/`)) throw new AppError("INVALID_INPUT", "Storage key does not belong to this lesson", 400); if (!course.sections.some((section) => section.lessons.some((lesson) => lesson._id.toString() === input.lessonId))) throw new AppError("LESSON_NOT_FOUND", "Lesson not found", 404); if (await CourseResource.exists({ storageKey: input.storageKey })) throw new AppError("RESOURCE_ALREADY_EXISTS", "This upload has already been registered", 409); return CourseResource.create({ ...input, courseId, fileUrl: input.storageKey }); },
  async listForCourse(courseId: string, user: PublicUser) { await connectToDatabase(); await courseForOwner(courseId, user); return CourseResource.find({ courseId }).sort({ createdAt: -1 }).lean(); },
  async listForLearner(courseId: string, user: PublicUser) { await connectToDatabase(); if (!Types.ObjectId.isValid(courseId)) throw new AppError("COURSE_NOT_FOUND", "Course not found", 404); const course = await Course.findById(courseId).select("instructorId").lean(); if (!course) throw new AppError("COURSE_NOT_FOUND", "Course not found", 404); const ownsCourse = user.role === "ADMIN" || course.instructorId.toString() === user.id; const enrolled = await enrollmentService.hasEnrollment(user.id, courseId); if (!ownsCourse && !enrolled) throw new AppError("COURSE_ACCESS_DENIED", "You do not have access to this course", 403); return CourseResource.find({ courseId }).sort({ createdAt: -1 }).lean(); },
  async getDownloadUrl(resourceId: string, user: PublicUser) { await connectToDatabase(); const resource = await CourseResource.findById(resourceId); if (!resource) throw new AppError("RESOURCE_NOT_FOUND", "Resource not found", 404); const course = await Course.findById(resource.courseId).select("instructorId").lean(); if (!course) throw new AppError("COURSE_NOT_FOUND", "Course not found", 404); const ownsCourse = canEditCourse(user, course.instructorId.toString()); const enrolled = await enrollmentService.hasEnrollment(user.id, resource.courseId.toString()); if (!ownsCourse && !enrolled) throw new AppError("COURSE_ACCESS_DENIED", "You do not have access to this resource", 403); return { name: resource.name, url: await storage.getSignedUrl(resource.storageKey) }; },
  async remove(resourceId: string, user: PublicUser) { await connectToDatabase(); const resource = await CourseResource.findById(resourceId); if (!resource) throw new AppError("RESOURCE_NOT_FOUND", "Resource not found", 404); await courseForOwner(resource.courseId.toString(), user); await storage.delete(resource.storageKey); await resource.deleteOne(); },
};
