import { z } from "zod";
import { COURSE_LEVELS, LESSON_TYPES } from "./course.types";
const objectId = z.string().regex(/^[a-f\d]{24}$/i, "Invalid identifier");
export const courseCreateSchema = z.object({ categoryId: objectId, title: z.string().trim().min(4).max(160), shortDescription: z.string().trim().min(10).max(300), description: z.string().trim().min(30).max(12000), thumbnailUrl: z.string().url().max(2000).optional(), level: z.enum(COURSE_LEVELS), language: z.string().trim().min(2).max(60), price: z.coerce.number().min(0).max(1_000_000), currency: z.literal("INR").default("INR") });
export const courseUpdateSchema = courseCreateSchema.partial().omit({ categoryId: true }).extend({ categoryId: objectId.optional() });
export const sectionSchema = z.object({ title: z.string().trim().min(2).max(160), description: z.string().trim().max(1000).optional(), position: z.coerce.number().int().min(1) });
export const lessonSchema = z.object({ title: z.string().trim().min(2).max(160), description: z.string().trim().max(2000).optional(), type: z.enum(LESSON_TYPES), videoUrl: z.string().url().max(2000).optional(), content: z.string().trim().max(20000).optional(), position: z.coerce.number().int().min(1), isPreview: z.boolean().default(false), durationSeconds: z.coerce.number().int().min(0).max(86_400).optional() }).superRefine((value, ctx) => { if (value.type === "VIDEO" && !value.videoUrl) ctx.addIssue({ code: "custom", message: "Video lessons require a video URL", path: ["videoUrl"] }); if (value.type === "TEXT" && !value.content) ctx.addIssue({ code: "custom", message: "Text lessons require content", path: ["content"] }); });
export const reorderSchema = z.object({ sections: z.array(z.object({ sectionId: objectId, position: z.coerce.number().int().min(1), lessonOrder: z.array(z.object({ lessonId: objectId, position: z.coerce.number().int().min(1) })) })).min(1) });
export const listQuerySchema = z.object({ q: z.string().trim().max(100).optional(), category: z.string().trim().max(100).optional(), level: z.enum(COURSE_LEVELS).optional(), minPrice: z.coerce.number().min(0).optional(), maxPrice: z.coerce.number().min(0).optional(), rating: z.coerce.number().min(0).max(5).optional(), sort: z.enum(["newest", "popular", "rating", "price_asc", "price_desc"]).default("newest"), page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).max(48).default(12) }).refine((query) => !query.minPrice || !query.maxPrice || query.minPrice <= query.maxPrice, { message: "Minimum price cannot exceed maximum price" });
