"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
type Lesson={_id:string;title:string;type:string;isPreview:boolean};type Section={_id:string;title:string;lessons:Lesson[]};
export function CurriculumEditor({courseId,sections}:{courseId:string;sections:Section[]}){
 const router=useRouter();const[notice,setNotice]=useState("");
 async function request(url:string,method:string,body?:unknown){const r=await fetch(url,{method,headers:body?{"content-type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined,credentials:"same-origin"});const j=await r.json();if(!r.ok)throw new Error(j.error?.message??"Request failed");router.refresh();}
 async function addSection(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await request(`/api/courses/${courseId}/sections`,"POST",{title:f.get("title"),position:sections.length+1});e.currentTarget.reset();}catch(e){setNotice(e instanceof Error?e.message:"Unable to add section");}}
 async function addLesson(e:FormEvent<HTMLFormElement>,sid:string,pos:number){e.preventDefault();const f=new FormData(e.currentTarget);try{await request(`/api/courses/${courseId}/sections/${sid}/lessons`,"POST",{title:f.get("title"),type:f.get("type"),videoUrl:f.get("videoUrl")||undefined,content:f.get("content")||undefined,isPreview:f.get("isPreview")==="on",position:pos});e.currentTarget.reset();}catch(e){setNotice(e instanceof Error?e.message:"Unable to add lesson");}}
 async function removeSection(id:string){if(!window.confirm("Delete this section and all its lessons?"))return;try{await request(`/api/courses/${courseId}/sections/${id}`,"DELETE");}catch(e){setNotice(e instanceof Error?e.message:"Unable to delete section");}}
 async function removeLesson(sid:string,lid:string){if(!window.confirm("Delete this lesson?"))return;try{await request(`/api/courses/${courseId}/sections/${sid}/lessons/${lid}`,"DELETE");}catch(e){setNotice(e instanceof Error?e.message:"Unable to delete lesson");}}
 async function editSection(s:Section){const title=window.prompt("Section title",s.title);if(!title?.trim()||title.trim()===s.title)return;try{await request(`/api/courses/${courseId}/sections/${s._id}`,"PATCH",{title:title.trim(),position:sections.findIndex(x=>x._id===s._id)+1});}catch(e){setNotice(e instanceof Error?e.message:"Unable to edit section");}}
 async function editLesson(sid:string,l:Lesson){const title=window.prompt("Lesson title",l.title);if(!title?.trim()||title.trim()===l.title)return;try{await request(`/api/courses/${courseId}/sections/${sid}/lessons/${l._id}`,"PATCH",{title:title.trim()});}catch(e){setNotice(e instanceof Error?e.message:"Unable to edit lesson");}}
 return <section className="rounded-xl border bg-[var(--surface)] p-6"><h2 className="text-xl font-bold">Curriculum</h2><p className="mt-1 text-sm text-[var(--muted)]">Add, edit, and remove sections and lessons.</p>{notice&&<p role="alert" className="mt-4 rounded bg-red-500/10 p-3 text-sm text-red-700">{notice}</p>}<div className="mt-6 space-y-5">{sections.map((s,i)=><article key={s._id} className="rounded-lg border p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">{i+1}. {s.title}</h3><div className="flex gap-2"><button type="button" onClick={()=>editSection(s)} className="rounded border px-2 py-1 text-xs">Edit</button><button type="button" onClick={()=>removeSection(s._id)} className="rounded border px-2 py-1 text-xs text-red-600">Delete</button></div></div><ul className="mt-3 space-y-2 text-sm">{s.lessons.map(l=><li key={l._id} className="flex items-center justify-between gap-2 rounded bg-black/5 px-3 py-2 dark:bg-white/5"><span>{l.title}<span className="ml-2 text-xs text-[var(--muted)]">{l.type}{l.isPreview?" · Preview":""}</span></span><div className="flex gap-2"><button type="button" onClick={()=>editLesson(s._id,l)} className="rounded border px-2 py-1 text-xs">Edit</button><button type="button" onClick={()=>removeLesson(s._id,l._id)} className="rounded border px-2 py-1 text-xs text-red-600">Delete</button></div></li>)}</ul><form className="mt-4 grid gap-2 sm:grid-cols-2" onSubmit={e=>addLesson(e,s._id,s.lessons.length+1)}><input name="title" required placeholder="Lesson title" className="rounded border bg-transparent px-3 py-2 text-sm"/><select name="type" className="rounded border bg-transparent px-3 py-2 text-sm"><option value="VIDEO">Video</option><option value="TEXT">Text</option></select><input name="videoUrl" type="url" placeholder="Video URL (for video)" className="rounded border bg-transparent px-3 py-2 text-sm"/><input name="content" placeholder="Text content (for text)" className="rounded border bg-transparent px-3 py-2 text-sm"/><label className="flex items-center gap-2 text-sm"><input name="isPreview" type="checkbox"/>Free preview</label><button className="rounded bg-indigo-600 px-3 py-2 text-sm font-medium text-white sm:col-span-2">Add lesson</button></form></article>)}</div><form className="mt-6 flex gap-2" onSubmit={addSection}><input name="title" required placeholder="New section title" className="flex-1 rounded border bg-transparent px-3 py-2"/><button className="rounded bg-black px-4 py-2 text-sm font-medium text-white dark:bg-white dark:text-black">Add section</button></form></section>;
}